build: false

environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
    - PYTHON: "C:/Python35"

init:
  - "ECHO %PYTHON%"

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install pytest-cov mock"

test_script:
  - "%PYTHON%/Scripts/py.test.exe -v --cov"
